server:
  port: 8081


spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
security.jwt.secret-key: da357602f738513187d27f541ea1815a4b09f8dc0f647551a3fd174b824331c4
  # 1h in millisecond
security.jwt.expiration-time: 3600000