spring:
  application:
    name: matching-engine-service
  datasource:
    url: jdbc:mysql://localhost:3306/matching-engine
    username: root
    password: root12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8083
peer-service:
  profile-service:
    url: http://localhost:8082
